# General settings
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
defaults:
  -
    scope:
      path: "archived"
    values:
      layout: "obsolete"
  -
    scope:
      path: "developers"
    values:
      layout: "docpage"
      navgroup: "developers"
  -
    scope:
      path: "documentation"
    values:
      layout: "docpage"
      navgroup: "documentation"
  -
    scope:
      path: "download"
    values:
      navgroup: "download"
  -
    scope:
      path: "help"
    values:
      layout: "docpage"
      navgroup: "help"
  -
    scope:
      path: ""
    values:
      layout: "base"
gems:
  - jekyll-redirect-from
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
  - Vagrantfile
